#!/bin/sh /etc/rc.common
# Wi-Fi card temperature -> "wifi-thermal" zone emul_temp (fan via kernel), see /usr/sbin/r4-wifi-temp

START=95
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/r4-wifi-temp
	procd_set_param respawn 3600 5 0
	procd_set_param stderr 1
	procd_close_instance
}
